### ISSUE TITLE
Image upload does not work in Firefox

### ISSUE THREAD

**Issue by warpech** [ckeditor/github-writer#168]
Trying to upload an image trough drag-n-drop or the toolbar icon, I get the following alert presented on the screenshot.

The image appears in the textarea for a while, then the alert shows up. After clicking "OK", the image disappears.

<img width="1505" alt="Screenshot 2020-05-06 at 16 28 32" src="https://user-images.githubusercontent.com/566463/81189364-c4651480-8fb6-11ea-9d94-3cd594df4c7e.png">

Firefox 75
Plugin version 1.0.0

This issue was written in Chrome, because I could not upload the screenshot in Firefox ;)

**Comment by fredck** [comment]
I believe the root of the problem is the same as in #167.

I was able to reproduce your upload problem by "breaking" GitHub Writer. Basically, I've changed the extension manifest ([these lines](https://github.com/ckeditor/github-writer/blob/6bf56c54d4620aa6aea3499f9260e3ee6fab2335/src/extension/manifest.json#L12-L13)) so it doesn't have permissions to make xhr requests.

You're not using the broken extension though, so it should work. **Unless** there is somethig specific to your Firefox installation that blocks the extension from doing xhr requests. This could be other extensions or configurations.

I'm not able to debug this from here, so it'll require a bit of you effort. I hope you don't mind.

### Option 1: disable all other add-ons

1.  Go to the add-ons page (Tools -> Add-ons) ([about:addons](about:addons)) and disable all other add-ons.
2.  Reload the page (or maybe even the browser).
3.  Try uploading again.

If this will work, you could then enable your extensions one by one and see which one breaks upload.

### Option 2: try a clean user profile

1.  Navigate to [about:profiles](about:profiles)
2.  Click "Create a New Profile" and give it a name.
3.  Under your new profile, click "Launch profile in new browser". You should see a new Firefox instance open.
4.  Go to that new Firefox instance. You'll notice that you have a "clean" browser... no add-ons and default preferences.
5.  In this clean browser:
    1.  Install GitHub Writer (https://addons.mozilla.org/en-US/firefox/addon/github-writer/)
    2.  Go to GiHub and try to upload an image again.

If this works, then there is something in your default user profile that breaks GitHub Writer. It can be a preference or something else. It would be great to know what it is.

---

I hope we'll figure this out. Thanks for the contribution!

**Comment by warpech** [comment]
You are right, the problem was in my Firefox profile. I had a "custom security" profile, whatever that means.

![](https://user-images.githubusercontent.com/566463/81313389-19249000-9088-11ea-9c28-fe156b04069f.png)

Changing to "standard security" fixed the problem. Now, even when I choose "custom security" again, the problem does not reappear. 🤷‍♂

The screenshot above was flawlessly added in Firefox now. Really nice UX

**Comment by fredck** [comment]
Well, that's great news then!

We can't do much about such kinds of settings, but knowing where to point people to in case of similar issues is a good plus.

Thanks a lot for the controbution @warpech!
