### ISSUE TITLE
Submit new issue button sometimes gets disabled

### ISSUE THREAD

**Issue by f1ames** [ckeditor/github-writer#172]
I wasn't able to find any repro scenario here yet, but was curious if anyone else stumbled upon this issue.

I have noticed it recently (like 2 weeks) and it's happening from time to time - when typing longer issues, submit button gets disabled at some point and I have to refresh the page to make it work again:

![](https://user-images.githubusercontent.com/1061942/81275012-60435e80-9051-11ea-9c49-4b89b95c9802.png)

No errors in the console though. :thinking: Switching between markdown/preview/writer, focusing/blurring editor doesn't help too.

Funny think it happened again when creating this issue. The button data attribute says `data-disable-invalid`:

![image](https://user-images.githubusercontent.com/1061942/81275409-f081a380-9051-11ea-852e-3363a4be5f6f.png)

Any ideas? Not even 100% sure if it's Github Writer related issue TBH.

**Comment by czerwonkabartosz** [comment]
I have noticed this same problem.

**Comment by fredck** [comment]
I think I've figured out a reliable way to reproduce it:

1.  On a new issue:
    1.  Set a title.
    2.  Type something in the editor.
2.  Move to markdown.
3.  Delete the typed title (button goes off).
4.  Re-type the title (button stays off). \<= issue
5.  Move back to rte (button stays stuck on off). \<= issue

Point 3 and 4 can be replaced to a programmatically call to `button.disabled = true` coming from anywhere. So maybe, if you switched to markdown when the issue happened, GH may have set `disabled` for some reason and it got stuck.

**The questions is: did you guys really switched to markdown and back to rte when the issue happened?**

**Comment by f1ames** [comment]
> The questions is: did you guys really switched to markdown and back to rte when the issue happened?

I did switch to markdown :see\_no\_evil: but didn't removed the title (I don't remember the last time I deleted the entire title - I usually do some adjustments only) so it's not the exactly same case :thinking:

**Comment by vokiel** [comment]
I don't remember exactly, but it did happen to me like two times maybe. As I do not switch to Markdown often (less and less as the plugin evolves), then it could be the path to reproduce.

**Comment by fredck** [comment]
I've hopefully fixed this issue.

As the reproduction steps are blurry, let's wait for the next release to see if things got stable. Please feel free to re-open this issue otherwise then.

**Comment by rjsdotorg** [comment]
I tried to submit at 
https://github.com/Ultimaker/Cura/issues/new?assignees=&labels=Type%3A+Bug&template=bugreport.yaml
and it never was enabled, at all. Tried twice with Brave and Edge, fail.

**Comment by jaydorsey** [comment]
Also seeing this with Chrome

I didn't see this mentioned in another issue, not sure if we want to re-open this or create a new one?

Also grabbed this screenshot:

![image](https://user-images.githubusercontent.com/191564/117902028-9e91e000-b29a-11eb-97a7-74ae3597d976.png)

Not 100% sure this isn't related to those failed calls out to Github stats because I'm seeing this on multiple repos now.

**Comment by psine** [comment]
Trying to attach a file before realizing it wasn't an allowable attachment did it for me.

**Comment by startakovsky** [comment]
Seems to be greyed out here even when filling out all the fields. https://github.com/bokeh/bokeh/issues/new?assignees=&labels=TRIAGE&template=bug_report.yml&title=%5BBUG%5D+

**Comment by pzelchenko** [comment]
This seems still to be happening in Firefox. I did not touch Markdown. I did try submitting and saw it was greyed out, then entered a title and it was still greyed out.

**Comment by ezawadzki** [comment]
Got the same issue on Brave Browser, get the shield down, then it worked.

**Comment by latot** [comment]
same.

**Comment by abdulfahad661** [comment]
> ezawadzki

same here disabled add blocker in chrome for github and it worked :)

**Comment by TAMHAN** [comment]
Also see the same issue here! Firefox on Ubuntu 20.04LTS

**Comment by garyross** [comment]
Now I see the issue. It's due to a  poor interface design. 

The submission is not available because the following is 'empty'. It certainly doesn't look empty - it looks prefilled. So if you don't notice that the text is actually an example rather than actual text then you can't submit. 
The issue is compounded by the fact there is no feedback indicating that the field has not been filled out. Make the background color red or something as a temporary fix. Better would be to put the example below the input. This is being too clever. 

<img width="502" alt="Screenshot 2024-04-19 at 15 57 28" src="https://github.com/ckeditor/github-writer/assets/173042/925c2c3c-2ca2-4be3-8c8b-8375e8c114ba">

**Comment by Soumilgit** [comment]
I have the same problem now May 2024.

**Comment by Rob190** [comment]
Same problem 13 June 2024. This is seriously confusing. I was trying to file a bug for an installer for software I've never used before so having boxes pre-filled with something that appears genuine led me to think I shouldn't change it.

**Comment by Adityavardhanjain** [comment]
Same problem. There should be an option to provide users info  regarding the reason why submission is not being considered. Its a minor but quite annoying of a bug.

**Comment by KatieRanhorn** [comment]
Same problem in Firefox. Worked in Chrome

**Comment by alexpmarsh** [comment]
Same problem in arc.

**Comment by Chris-Pr** [comment]
same problem chrome right now.

**Comment by xerces8** [comment]
Happened to me what [garyross](https://github.com/garyross) said on Apr 19: 
https://github.com/ckeditor/github-writer/issues/172#issuecomment-2065885583

also see: https://github.com/orgs/community/discussions/12820

As this issue is closed, is there an open one? For the "submit button is disable but there is no indication why" thing.
