### ISSUE TITLE
Left click on link opens it in the same tab

### ISSUE THREAD

**Issue by f1ames** [ckeditor/github-writer#189]
I see there is an issue with `Cmd`/`Ctrl` + click, but for me it just happens on regular left click:

![](https://user-images.githubusercontent.com/1061942/82339525-6a207680-99ee-11ea-8ee1-7b694a0873ad.gif)

This is problematic because when you try to edit a link and click on it - it redirects to linked page which is quite confusing.

The funny thing is that even if I refresh the page it still happens and also opening new issue in this repository (`ckeditor4-vue)` and copy/pasting this content has the same effect. However, when this is copy/pasted to another repo (checked here) it works fine (balloon appears instead of redirect). Not really sure what's the difference - I checked editor HTML and it is the same :thinking: :confused: Really strange.

OS: Linux Mint 19.2  
Browser: Chrome 81.0.4044.138  
Extension version: 1.1.0  
Markdown used in the sample above:

```
## Are you reporting a feature request or a bug?

Task

## Provide detailed reproduction steps (if any)

Before [`1.0.0` release](https://github.com/ckeditor/ckeditor4-vue/milestone/2) we need to:

*   [ ] Check [`1.0.0` changelog](https://github.com/ckeditor/ckeditor4-vue/blob/master/CHANGELOG.md#ckeditor4-vue-100)
*   [ ] Conclude docs updates - #7
```

@fredck can you check with the above Markdown in this and `ckeditor4-vue` repo? Does this happen anywhere for you?

**Comment by f1ames** [comment]
Cleared cache and it still happens :thinking:

**Comment by fredck** [comment]
Confirmed on Chrome/Mac as well. It happens only on the ckeditor4-vue repo, exactly as described. That's weird :thinking:

**Comment by fredck** [comment]
Figured out the problem:

1.  The link points to a file in the ckeditor4-vue repo... so, the same repo you're in.
2.  GitHub uses pjax for links inside the content... in this case, the editor editable counts as plain content for GitHub, because it doesn't know its an editor.
3.  When you click the link, the pjax listener catches it and replaces the content of the page with content from the server.

So, the trick here will be just stopping pjax listeners to watch for the editable content.
