### ISSUE TITLE
Unable to create a code using backticks if preceded by a parentheses

### ISSUE THREAD

**Issue by oleq** [ckeditor/github-writer#223]
This thing is driving me crazy because I use code in parentheses all the time when writing issues 😛 Only today I stumbled upon this problem like 10-20 times.

```
some text (`someCode` <- this backtick does not create <code>
some text ( `someCode` <- this backtick does create <code> (note the space after the parentheses
```

It works fine in the CKEditor 5 [Autoformatting sample](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/autoformat.html), though.

**Comment by jodator** [comment]
Similar, but iniside brackets: 

```
using `||` 
```

is not corrected: \`||\`

**Comment by fredck** [comment]
> It works fine in the CKEditor 5 [Autoformatting sample](https://ckeditor5.github.io/docs/nightly/ckeditor5/latest/features/autoformat.html), though.

Unfortunately, due to limitations in the default plugin implementation, a brand new auto-format plugin has been introduced in GitHub Writer. It doesn't have a 1:1 match with the original plugin features (misses some, adds others) but of course it can be enhanced and both the parenthesis and quote cases are very valid.
