### ISSUE TITLE
GH Writer doesn't load in the review comment textarea

### ISSUE THREAD

**Issue by Dumluregn** [ckeditor/github-writer#345]
## 📝 Provide detailed reproduction steps (if any)

1.  Open any PR.
2.  Go to `Files changed` tab.
3.  Click `Review changes` button.

### ✔️ Expected result

GH Writer should be loaded in the popping editable.

### ❌ Actual result

No GH Writer:

![](https://user-images.githubusercontent.com/10883184/183042309-8fb80af0-9ea7-4a12-ae97-ad194def383d.png)

### ❓ Possible solution

AFAICS the selector assigned for the `ReviewEditor` class (`div.pull-request-review-menu > form`) is outdated - it doesn't match any element on the site. Probably adjusting it should be enough to solve the issue.

It could be a good idea to ensure that all the other editor types still have proper selectors (probably so as do similar issues are reported, but still).

## 📃 Other details

*   Browser: any
*   OS: any

---

If you'd like to see this fixed sooner, add a 👍 reaction to this post.

**Comment by mateuszzagorski** [comment]
Updating the selector should resolve the issue for ReviewEditor as you've mentioned.

We should consider applying some tweaks to the styling of it, because now after it's loaded it looks like this:  
  
Normal view:

![](https://user-images.githubusercontent.com/11699569/183584683-63198e4e-4e42-4944-a072-24bbe89098c9.png)

Markdown view:

![](https://user-images.githubusercontent.com/11699569/183584741-4087e968-f076-4963-abfd-261a8ecb8f81.png)

**Comment by Dumluregn** [comment]
Since you've said that `.pull-request-review-menu` class is currently added by Writer, I guess there may also be some custom CSS attached? Then it should be enough to just change the selectors there too.
