### ISSUE TITLE
Link to the site is wrong

### ISSUE THREAD

**Issue by wwalc** [ckeditor/github-writer#356]
Is: [https://ckeditor.com/?github-writer](https://ckeditor.com/?github-writer)

Should be: [https://ckeditor.com/github-writer](https://ckeditor.com/github-writer)

![](https://user-images.githubusercontent.com/545175/186145070-5efb27b7-0f29-4546-9524-d030f7aded1c.png)

**Comment by Dun-sin** [comment]
Hi, can I work on this? Also, where exactly is the change needed

**Comment by mlewand** [comment]
@Dun-sin you're welcome to do so. I won't search for exact line number because it should be very simple. My best bet is just to:

1.  clone the repo
2.  use find in all files feature of your text editor
3.  search for [`https://ckeditor.com/?github-writer`](https://ckeditor.com/?github-writer) string

This should be enough to find it :slightly\_smiling\_face:
